# Generated by Django 4.2.6 on 2023-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default=3808, max_length=4, verbose_name='ключ регистрации'),
        ),
    ]
