# Generated by Django 4.2.6 on 2023-10-29 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2023, 10, 29), verbose_name='дата создания'),
        ),
    ]
