# Generated by Django 4.2.6 on 2023-11-12 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
    ]
