# Generated by Django 4.2.6 on 2023-11-19 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='наименование')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='наименование')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение (превью)')),
                ('category', models.CharField(max_length=90, verbose_name='категория')),
                ('purchase_price', models.IntegerField(verbose_name='цена за покупку')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего изменения')),
                ('is_published', models.CharField(choices=[('published', 'опубликовано'), ('not_published', 'не опубликовано')], default='not_published', max_length=20, verbose_name='статус публикации')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'permissions': [('set_published', 'can published posts'), ('change_description', 'Can change description'), ('set_category', 'Can set category')],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='номер версии')),
                ('name_version', models.CharField(max_length=90, verbose_name='название версии')),
                ('flag_of_the_cur_ver', models.BooleanField(verbose_name='признак текущей версии')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
